# Generated by Django 4.0.4 on 2022-07-26 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DeliveryApp', '0002_rename_profilerating_delegaterating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newdelegate',
            name='CarImage',
        ),
        migrations.RemoveField(
            model_name='newdelegate',
            name='DrivingLicense',
        ),
        migrations.RemoveField(
            model_name='newdelegate',
            name='PersonalImage',
        ),
        migrations.CreateModel(
            name='CancellingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cancel', models.CharField(choices=[('السعر غير مناسب', 'السعر غير مناسب'), ('المندوب غير مناسب', 'المندوب غير مناسب'), ('غير ذلك', 'غير ذلك')], max_length=250)),
                ('Description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
