# Generated by Django 4.0.4 on 2022-07-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0004_delegaterating_description_newdelegate_carimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdelegate',
            name='CarImage',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='newdelegate',
            name='PhoneNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
