# Generated by Django 4.0.6 on 2022-07-26 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0005_alter_newdelegate_carimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delegaterating',
            name='profile',
        ),
    ]
