# Generated by Django 4.0.6 on 2022-07-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0006_remove_delegaterating_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegaterating',
            name='Description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='delegaterating',
            name='rate',
            field=models.CharField(blank=True, choices=[('4', 'excellent'), ('3 ', 'very good'), ('2', 'good'), ('1', 'bad')], max_length=250),
        ),
    ]
